version: '3'
services:
  fastapi:
    container_name: fastapi_inventory
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - .:/home/dev/inventory-system/
    depends_on:
      - postgres-db
    environment:
      - DATABASE_URL

  postgres-db:
    container_name: postgres_inventory
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

networks:
  mynetwork:
